#!/command/with-contenv bash
source /run/virtualme/config.env
export DISPLAY="$VM_EFFECTIVE_DISPLAY"
until xdpyinfo >/dev/null 2>&1; do sleep 0.2; done
exec openbox --config-file /etc/virtualme/openbox-rc.xml
