// @ts-nocheck
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { access, readFile, readdir } from "node:fs/promises";
import { join, relative } from "node:path";
import test from "node:test";

const root = new URL("../", import.meta.url);
const docs = new URL("../docs/", import.meta.url);
const required = [
  "package.json", "package-lock.json", "astro.config.mjs", "tsconfig.json", "README.md",
  "public/.nojekyll", "public/favicon.svg", "public/social-card.jpg",
  "scripts/ensure-generated.mjs", "scripts/make-404.mjs", "scripts/verify-build.mjs",
  "src/layouts/BaseLayout.astro", "src/layouts/DocsLayout.astro", "src/layouts/EditorialLayout.astro",
  "src/pages/index.astro", "src/pages/guide.astro", "src/pages/architecture.astro",
  "src/pages/configuration.astro", "src/pages/blog/index.astro", "src/pages/blog/[...slug].astro",
  "src/pages/about.astro", "src/pages/no-more-bills.astro", "src/pages/404.astro",
  "src/generated/config-reference.json", "src/generated/themes.json", "src/styles/generated-themes.css",
  "src/content/blog/welcome.md", "test/browser.test.mjs",
];

test("docs package is isolated, exact-pinned, and complete", async () => {
  await Promise.all(required.map((path) => access(new URL(path, docs))));
  const pkg = JSON.parse(await readFile(new URL("package.json", docs)));
  assert.equal(pkg.private, true);
  assert.equal(pkg.type, "module");
  assert.deepEqual(pkg.engines, { node: ">=22.12.0" });
  assert.deepEqual(pkg.devDependencies, {
    "@astrojs/check": "0.9.9",
    "@playwright/test": "1.62.0",
    astro: "7.1.3",
    typescript: "6.0.3",
  });
  const lock = JSON.parse(await readFile(new URL("package-lock.json", docs)));
  assert.equal(lock.lockfileVersion, 3);
  assert.ok(Object.values(lock.packages).some((value) => value?.integrity));
  const rootPkg = JSON.parse(await readFile(new URL("package.json", root)));
  assert.ok(!rootPkg.dependencies || Object.keys(rootPkg.dependencies).length === 0);
});

test("Astro config and generated configuration match production contract", async () => {
  const config = await readFile(new URL("astro.config.mjs", docs), "utf8");
  assert.match(config, /site:\s*"https:\/\/mayanklahiri\.github\.io"/);
  assert.match(config, /base:\s*"\/virtualme"/);
  assert.match(config, /output:\s*"static"/);
  assert.match(config, /trailingSlash:\s*"always"/);
  assert.match(config, /baseAwareMarkdownLinks/);
  const reference = JSON.parse(await readFile(new URL("src/generated/config-reference.json", docs)));
  assert.equal(reference.schemaVersion, 1);
  assert.match(reference.schemaSha256, /^[0-9a-f]{64}$/);
  assert.ok(reference.sections.length >= 9);
  assert.ok(reference.sections.some((section) =>
    section.settings.some((setting) => setting.path === "llama.contextTokens")));
  const allowedChats = reference.sections.flatMap((section) => section.settings)
    .find((setting) => setting.path === "integrations.telegram.allowedChatIds");
  assert.equal(allowedChats.item.type, "string");
  assert.equal(allowedChats.item.constraints.pattern, "^-?[1-9][0-9]*$");
  assert.ok(allowedChats.item.overview);
  assert.ok(Array.isArray(allowedChats.item.details));
  assert.match(await readFile(new URL("src/styles/generated-themes.css", docs), "utf8"), /Generated by scripts\/generate-themes\.mjs/);
  const page = await readFile(new URL("src/pages/configuration.astro", docs), "utf8");
  for (const field of ["choices", "constraints", "secretPolicy", "tradeoffs", "examples", "links", "consoleDeepLink", "item"]) {
    assert.match(page, new RegExp(`setting\\.${field}|section\\.${field}`), `configuration page omits ${field}`);
  }
  assert.match(page, /IntersectionObserver/);
  assert.match(page, /config-section-picker/);
  assert.match(page, /searchParams\.delete\("q"\)/);
});

test("authored Astro sources stay docs-local and contain no remote resources", async () => {
  async function walk(directory) {
    const entries = await readdir(directory, { withFileTypes: true });
    return (await Promise.all(entries.map((entry) => entry.isDirectory()
      ? walk(new URL(`${entry.name}/`, directory))
      : [new URL(entry.name, directory)]))).flat();
  }
  const files = (await walk(new URL("src/", docs))).filter((url) => /\.(astro|ts|js|md|mdx)$/.test(url.pathname));
  for (const file of files) {
    const text = await readFile(file, "utf8");
    assert.doesNotMatch(text, /from\s+["'][^"']*(?:\.\.\/){3}|readFile|fetch\s*\(/, file.pathname);
    assert.doesNotMatch(text, /\bsrc=["']https?:\/\//, file.pathname);
    assert.doesNotMatch(text, /(?:href|src)=["']\/(?!\/)/, file.pathname);
    if (/\.(?:md|mdx)$/.test(file.pathname)) {
      for (const match of text.matchAll(/\[[^\]]+\]\(([^)]+)\)/g)) {
        const target = match[1];
        assert.doesNotMatch(target, /^\/virtualme\//, file.pathname);
        if (!/^(?:https?:|mailto:|tel:|#)/.test(target)) assert.match(target, /^site:[a-z0-9][a-z0-9/.-]*$/i, file.pathname);
      }
    }
  }
});

test("README and site crosslink with exact copyright", async () => {
  assert.match(await readFile(new URL("README.md", root), "utf8"), /\[Documentation\]\(https:\/\/mayanklahiri\.github\.io\/virtualme\/\)/);
  const footer = await readFile(new URL("src/components/PageFooter.astro", docs), "utf8");
  assert.match(footer, /© 2026/);
  assert.match(footer, /https:\/\/www\.linkedin\.com\/in\/mayanklahiri\//);
  const nav = await readFile(new URL("src/components/PageHeader.astro", docs), "utf8");
  assert.match(nav, /https:\/\/github\.com\/mayanklahiri\/virtualme/);
  assert.match(nav, /https:\/\/github\.com\/mayanklahiri\/virtualme#readme/);
});

test("disabled/enabled analytics builds are complete and disabled output is deterministic", async () => {
  const cwd = new URL("../docs/", import.meta.url).pathname;
  const build = (measurementId = "") => spawnSync("npm", ["run", "build"], {
    cwd,
    encoding: "utf8",
    env: { ...process.env, PUBLIC_GA_MEASUREMENT_ID: measurementId },
  });
  async function htmlFiles(directory) {
    const result = [];
    async function visit(path) {
      for (const entry of await readdir(path, { withFileTypes: true })) {
        const child = join(path, entry.name);
        if (entry.isDirectory()) await visit(child);
        else if (entry.name.endsWith(".html")) result.push(child);
      }
    }
    await visit(directory);
    return result.sort((a, b) => Buffer.from(a).compare(Buffer.from(b)));
  }
  async function digestTree(directory) {
    const result = new Map();
    async function visit(path) {
      for (const entry of await readdir(path, { withFileTypes: true })) {
        const child = join(path, entry.name);
        if (entry.isDirectory()) await visit(child);
        else result.set(relative(directory, child), createHash("sha256").update(await readFile(child)).digest("hex"));
      }
    }
    await visit(directory);
    return result;
  }
  let run = build();
  assert.equal(run.status, 0, run.stderr);
  const first = await digestTree(join(cwd, "dist"));
  for (const file of await htmlFiles(join(cwd, "dist"))) assert.doesNotMatch(await readFile(file, "utf8"), /googletagmanager|google-analytics|dataLayer|gtag\(/);
  run = build();
  assert.equal(run.status, 0, run.stderr);
  assert.deepEqual(await digestTree(join(cwd, "dist")), first);
  run = build("G-TEST1234");
  assert.equal(run.status, 0, run.stderr);
  for (const file of await htmlFiles(join(cwd, "dist"))) {
    const html = await readFile(file, "utf8");
    assert.equal((html.match(/googletagmanager\.com\/gtag\/js\?id=G-TEST1234/g) ?? []).length, 1, file);
    assert.equal((html.match(/gtag\("config",\s*analyticsMeasurementId\)/g) ?? []).length, 1, file);
  }
  run = build("not-valid");
  assert.notEqual(run.status, 0);
  const verifier = await readFile(new URL("scripts/verify-build.mjs", docs), "utf8");
  assert.doesNotMatch(verifier, /G-TEST1234/);
  assert.match(verifier, /committedAnalyticsId/);
});
