import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);

test("release workflow requires curated notes and preserves immutability", async () => {
  const workflow = await readFile(new URL(".github/workflows/release.yml", root), "utf8");

  assert.match(workflow, /Immutability — version tags absent from Docker Hub/);
  assert.match(workflow, /Immutability — version absent from npm/);
  assert.match(
    workflow,
    /test -s "release-notes\/\$GITHUB_REF_NAME\.md" \|\| \{ echo "missing release-notes\/\$GITHUB_REF_NAME\.md" >&2; exit 1; \}/,
  );
  assert.match(workflow, /--notes-file "release-notes\/\$GITHUB_REF_NAME\.md"/);
  assert.match(workflow, /releases\/generate-notes/);
  assert.doesNotMatch(workflow, /^\s+--generate-notes$/m);
});

test("release workflow publishes the committed Docker Hub overview", async () => {
  const [workflow, overview] = await Promise.all([
    readFile(new URL(".github/workflows/release.yml", root), "utf8"),
    readFile(new URL("docker/DOCKERHUB.md", root), "utf8"),
  ]);

  assert.match(workflow, /jq -n --rawfile body docker\/DOCKERHUB\.md/);
  assert.match(workflow, /curl -fsS -X PATCH/);
  assert.match(workflow, /repositories\/\$IMAGE\//);
  assert.match(overview, /npx virtualme start/);
  assert.match(overview, /No cloud, no\naccounts, no telemetry\./);
  assert.match(overview, /trusted private network only\./);
});

test("release skill and npm metadata retain their contracts", async () => {
  const [skill, packageText, notesReadme] = await Promise.all([
    readFile(new URL(".cursor/skills/do-release/SKILL.md", root), "utf8"),
    readFile(new URL("package.json", root), "utf8"),
    readFile(new URL("release-notes/README.md", root), "utf8"),
  ]);
  const pkg = JSON.parse(packageText);

  assert.match(
    skill,
    /confirm the tone-only rule \(no names,\n\s+places, quotes, plot, or numbers from the source archetype\)/,
  );
  assert.match(
    skill,
    /— Marvin, Release Bot\. The commit list below is generated by machines with less personality\./,
  );
  assert.deepEqual(pkg.keywords, [
    "agent", "local-llm", "docker", "automation", "self-hosted", "llama-cpp",
    "browser-automation", "privacy",
  ]);
  assert.ok(pkg.files.includes("README.md"));
  assert.match(notesReadme, /`vX\.Y\.Z\.md`/);
  assert.match(notesReadme, /authored by `\/do-release`/);
});
