#!/command/with-contenv bash
source /run/virtualme/config.env
exec valkey-server --bind "$VM_EFFECTIVE_VALKEY_HOST" --port "$VM_EFFECTIVE_VALKEY_PORT" \
  --save "" --appendonly yes --dir "$VM_DATA_DIR/valkey"
