package agent

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestEncodeYAMLOrderAndQuoting(t *testing.T) {
	value := map[string]any{
		"body": []any{map[string]any{
			"sel":  `body > div:nth-of-type(1)`,
			"tag":  "h1",
			"text": "Hello \"world\"\nline two",
		}},
		"title": "Example",
		"url":   "https://example.com/",
		"head": map[string]any{
			"canonical": "https://example.com/",
			"lang":      "en",
		},
	}
	got := encodeYAML(value)
	wantParts := []string{
		`title: "Example"`,
		`url: "https://example.com/"`,
		"head:",
		`lang: "en"`,
		"body:",
		`- tag: "h1"`,
		`text: "Hello \"world\"\nline two"`,
	}
	for _, part := range wantParts {
		if !strings.Contains(got, part) {
			t.Fatalf("missing %q in:\n%s", part, got)
		}
	}
	if strings.Index(got, "title:") > strings.Index(got, "url:") {
		t.Fatalf("title must precede url:\n%s", got)
	}
}

func TestDigestToYAMLBudgetMarker(t *testing.T) {
	body := make([]any, 0, 200)
	for range 200 {
		body = append(body, map[string]any{
			"tag":  "p",
			"sel":  "body > p:nth-of-type(1)",
			"text": strings.Repeat("x", 120),
		})
	}
	digest := map[string]any{
		"title": "Big",
		"url":   "https://example.com/",
		"head":  map[string]any{},
		"body":  body,
	}
	got := digestToYAML(digest)
	if len(got) > readPageCap {
		t.Fatalf("digest length %d exceeds cap %d", len(got), readPageCap)
	}
	if !strings.Contains(got, "truncated: page digest exceeded budget") {
		t.Fatalf("expected budget marker in truncated digest")
	}
}

func TestDigestToYAMLNoMarkerWhenUntruncated(t *testing.T) {
	// Observed red before the fix: every digest, truncated or not, gained the
	// "exceeded budget" marker because nothing tracked whether nodes dropped.
	digest := map[string]any{
		"title": "T", "url": "https://example.com/",
		"head": map[string]any{"lang": "en"},
		"body": []any{map[string]any{"tag": "h1", "sel": "body > h1:nth-of-type(1)", "text": "Hi"}},
	}
	got := digestToYAML(digest)
	if strings.Contains(got, "exceeded budget") {
		t.Fatalf("spurious truncation marker on small digest:\n%s", got)
	}
}

func TestDigestToYAMLPrunesEmptyContainers(t *testing.T) {
	digest := map[string]any{
		"title": "T", "url": "https://example.com/",
		"head": map[string]any{},
		"body": []any{map[string]any{
			"tag": "ul", "sel": "body > ul:nth-of-type(1)",
			"items": []any{}, "text": "",
		}},
	}
	got := digestToYAML(digest)
	if strings.Contains(got, "{}") || strings.Contains(got, "[]") {
		t.Fatalf("flow-style empty container emitted:\n%s", got)
	}
	if strings.Contains(got, "head:") || strings.Contains(got, "items:") || strings.Contains(got, "text:") {
		t.Fatalf("empty keys survived pruning:\n%s", got)
	}
}

func TestEncodeYAMLGoldenFixture(t *testing.T) {
	digest := map[string]any{
		"title": "Golden \"Digest\"\nLine two",
		"url":   "https://example.com/golden",
		"head": map[string]any{
			"lang": "en",
			"og":   map[string]any{"image": "https://example.com/i.png", "title": "OG"},
		},
		"body": []any{
			map[string]any{
				"tag": "h1", "sel": "body > h1:nth-of-type(1)", "text": "Héading ünïcode",
			},
			map[string]any{
				"tag": "table", "sel": "body > table:nth-of-type(1)",
				"rows": []any{[]any{"A", "B"}, []any{"1", ""}},
			},
			map[string]any{
				"tag": "ul", "sel": "body > ul:nth-of-type(1)",
				"items": []any{map[string]any{"text": "Item", "href": "https://example.com/item"}},
			},
			map[string]any{
				"tag": "p", "sel": "body > p:nth-of-type(1)", "text": "para",
				"children": []any{map[string]any{
					"tag": "a", "sel": "body > p:nth-of-type(1) > a:nth-of-type(1)",
					"href": "https://example.com/a", "text": "link",
				}},
			},
		},
	}
	got := encodeYAML(digest)
	// Golden for the Node parser round-trip test (regenerated by this test).
	goldenPath := filepath.Join("..", "..", "..", "test", "fixtures", "readpage-digest.golden.yaml")
	if err := os.WriteFile(goldenPath, []byte(got), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestReadPageExpressionUsesEmbeddedScript(t *testing.T) {
	expr := readPageExpression()
	if !strings.Contains(expr, "NODE_BUDGET") {
		t.Fatalf("embedded read page script missing: %q", expr[:min(80, len(expr))])
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
