import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ids = ["modern", "editorial", "terminal", "warm", "contrast", "arctic", "solar", "studio"];
const topKeys = ["schemaVersion", "defaultTheme", "defaultVariant", "themes"];
const themeKeys = ["id", "label", "swatch", "typography", "shape", "light", "dark"];
const typeKeys = ["heading", "body", "mono", "scale"];
const shapeKeys = ["radius", "motion", "iconStroke"];
const colorKeys = ["bg", "surface", "fg", "muted", "accent", "accentFg", "ok", "err", "border", "brandA", "brandB", "p1", "p2", "p3", "p4", "p5", "p6", "p7", "p8"];
const generated = "scripts/generate-themes.mjs from common/themes/themes.json; DO NOT EDIT";
/** @typedef {any} ThemeSource */
/** @typedef {{error?: (message: string) => void}} GeneratorIO */
const paths = {
  controllerCss: "controller/web/static/css/generated-themes.css",
  docsCss: "docs/src/styles/generated-themes.css",
  docsJson: "docs/src/generated/themes.json",
  controllerRegistry: "controller/web/static/js/generated-themes.js",
  controllerBoot: "controller/web/static/js/generated-theme-boot.js",
};

/** @param {string} pointer @param {string} message @returns {never} */
function fail(pointer, message) {
  throw new Error(`${pointer || "/"}: ${message}`);
}
/** @param {any} value @param {string[]} keys @param {string} pointer */
function exactKeys(value, keys, pointer) {
  if (!value || typeof value !== "object" || Array.isArray(value)) fail(pointer, "must be an object");
  for (const key of keys) if (!(key in value)) fail(`${pointer}/${key}`, "is required");
  for (const key of Object.keys(value)) if (!keys.includes(key)) fail(`${pointer}/${key}`, "unknown field");
}

/** @param {any} input @returns {ThemeSource} */
export function loadThemes(input) {
  exactKeys(input, topKeys, "");
  if (input.schemaVersion !== 1) fail("/schemaVersion", "must be 1");
  if (input.defaultTheme !== "modern") fail("/defaultTheme", "must be modern");
  if (input.defaultVariant !== "auto") fail("/defaultVariant", "must be auto");
  if (!Array.isArray(input.themes) || input.themes.length !== 8) fail("/themes", "must contain exactly eight themes");
  const seen = new Set();
  /** @type {any[]} */
  const themes = input.themes;
  themes.forEach((theme, index) => {
    const pointer = `/themes/${index}`;
    exactKeys(theme, themeKeys, pointer);
    if (theme.id !== ids[index]) fail(`${pointer}/id`, `wrong order; expected ${ids[index]}`);
    if (!/^[a-z][a-z0-9-]*$/.test(theme.id)) fail(`${pointer}/id`, "invalid ID");
    if (seen.has(theme.id)) fail(`${pointer}/id`, "duplicate ID");
    seen.add(theme.id);
    if (typeof theme.label !== "string" || !theme.label.trim()) fail(`${pointer}/label`, "must be non-empty");
    if (!Array.isArray(theme.swatch) || theme.swatch.length !== 2) fail(`${pointer}/swatch`, "must have two colors");
    exactKeys(theme.typography, typeKeys, `${pointer}/typography`);
    exactKeys(theme.shape, shapeKeys, `${pointer}/shape`);
    for (const key of ["heading", "body", "mono"]) if (!theme.typography[key]) fail(`${pointer}/typography/${key}`, "must be non-empty");
    for (const [key, value] of [["scale", theme.typography.scale], ["iconStroke", theme.shape.iconStroke]]) {
      if (!Number.isFinite(value) || value <= 0) fail(`${pointer}/${key}`, "must be finite and positive");
    }
    if (!/^-?(?:\d+|\d*\.\d+)(?:px|rem|em|s|ms)$/.test(theme.shape.radius)) fail(`${pointer}/shape/radius`, "requires a CSS unit");
    if (!/^-?(?:\d+|\d*\.\d+)(?:s|ms)$/.test(theme.shape.motion)) fail(`${pointer}/shape/motion`, "requires a time unit");
    for (const [variant, colors] of [["light", theme.light], ["dark", theme.dark]]) {
      exactKeys(colors, colorKeys, `${pointer}/${variant}`);
      for (const key of colorKeys) if (!/^#[0-9a-f]{6}$/.test(colors[key])) fail(`${pointer}/${variant}/${key}`, "must be #rrggbb");
    }
    for (const [swatchIndex, color] of theme.swatch.entries()) if (!/^#[0-9a-f]{6}$/.test(color)) fail(`${pointer}/swatch/${swatchIndex}`, "must be #rrggbb");
  });
  return structuredClone(input);
}

/** @param {string} name */
const cssName = (name) => name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
/** @param {ThemeSource} source */
function renderCss(source) {
  const lines = ["/* Generated by scripts/generate-themes.mjs from common/themes/themes.json.", " * DO NOT EDIT. */"];
  for (const theme of source.themes) {
    lines.push(`[data-theme="${theme.id}"] {`);
    for (const [key, value] of Object.entries(theme.typography)) lines.push(`  --font-${key}: ${value};`);
    lines.push(`  --radius: ${theme.shape.radius};`, `  --motion: ${theme.shape.motion};`, `  --icon-stroke: ${theme.shape.iconStroke};`, "}");
    for (const variant of ["light", "dark"]) {
      lines.push(`[data-theme="${theme.id}"][data-variant="${variant}"] {`);
      for (const key of colorKeys) lines.push(`  --${cssName(key)}: ${theme[variant][key]};`);
      lines.push("}");
    }
    lines.push(`.theme-${theme.id}>span:first-child {`, `  background: linear-gradient(135deg, ${theme.swatch[0]} 50%, ${theme.swatch[1]} 50%);`, "}");
  }
  return `${lines.join("\n")}\n`;
}

/** @param {ThemeSource} source @returns {Map<string, string>} */
export function renderOutputs(source) {
  const css = renderCss(source);
  /** @type {any[]} */
  const themes = source.themes;
  const docs = { _generated: generated, schemaVersion: source.schemaVersion, defaultTheme: source.defaultTheme, defaultVariant: source.defaultVariant, themes: themes.map((theme) => ({ id: theme.id, label: theme.label, swatch: theme.swatch })) };
  const registry = `// Generated by ${generated}\nexport const themes = Object.freeze(${JSON.stringify(docs.themes)}.map(Object.freeze));\nexport const themeIds = Object.freeze(themes.map(({id})=>id));\n`;
  const boot = `// Generated by ${generated}\nwindow.VIRTUALME_THEMES=Object.freeze(${JSON.stringify(ids)});\n`;
  return new Map([
    [paths.controllerCss, css],
    [paths.docsCss, css],
    [paths.docsJson, `${JSON.stringify(docs, null, 2)}\n`],
    [paths.controllerRegistry, registry],
    [paths.controllerBoot, boot],
  ]);
}

/**
 * @param {Map<string, string>} destinations
 * @param {{check?: boolean, error?: (message: string) => void}} [options]
 */
export async function synchronize(destinations, { check = false, error = console.error } = {}) {
  const stale = [];
  for (const [path, bytes] of destinations) {
    let current;
    try { current = await readFile(path, "utf8"); } catch { current = undefined; }
    if (current !== bytes) stale.push(path);
  }
  if (check) {
    stale.forEach(error);
    return stale.length ? 1 : 0;
  }
  for (const path of stale) {
    const bytes = destinations.get(path);
    if (bytes === undefined) continue;
    await mkdir(dirname(path), { recursive: true });
    const temporary = `${path}.tmp`;
    await writeFile(temporary, bytes);
    await rename(temporary, path);
  }
  return 0;
}

/** @param {string[]} [argv] @param {GeneratorIO} [io] */
export async function main(argv = process.argv.slice(2), io = {}) {
  if (argv.some((argument) => argument !== "--check") || argv.length > 1) {
    (io.error ?? console.error)("Usage: node scripts/generate-themes.mjs [--check]");
    return 2;
  }
  try {
    const source = loadThemes(JSON.parse(await readFile(resolve(root, "common/themes/themes.json"), "utf8")));
    const outputs = new Map([...renderOutputs(source)].map(([path, bytes]) => [resolve(root, path), bytes]));
    return synchronize(outputs, { check: argv[0] === "--check", error: io.error });
  } catch (error) {
    (io.error ?? console.error)(error instanceof Error ? error.message : String(error));
    return 1;
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) process.exitCode = await main();
