// Command configctl validates and exports the master configuration.
package main

import (
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/mayanklahiri/virtualme/controller/internal/config"
)

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "configctl:", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	if len(args) == 0 {
		return errors.New("usage: configctl preflight|docs")
	}
	switch args[0] {
	case "preflight":
		return preflight(args[1:])
	case "docs":
		return docs(args[1:])
	default:
		return fmt.Errorf("unknown command %q", args[0])
	}
}

func preflight(args []string) error {
	flags := flag.NewFlagSet("preflight", flag.ContinueOnError)
	dataDir := flags.String("data-dir", "", "bootstrap data directory")
	serviceEnv := flags.String("service-env", "", "service environment output")
	mailDir := flags.String("mail-dir", "", "mail configuration directory")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if *dataDir == "" || *serviceEnv == "" || *mailDir == "" || flags.NArg() != 0 {
		return errors.New("preflight requires --data-dir, --service-env, and --mail-dir")
	}
	loaded, err := config.Load(config.Options{DataDir: *dataDir, Warn: func(message string) {
		fmt.Fprintln(os.Stderr, message)
	}})
	if err != nil {
		return err
	}
	if err := config.AtomicWrite(*serviceEnv, serviceEnvironment(loaded)); err != nil {
		return fmt.Errorf("service environment: %w", err)
	}
	return writeMail(loaded, *mailDir)
}

func serviceEnvironment(loaded *config.Loaded) []byte {
	cfg := loaded.Config
	values := [][2]string{
		{"VM_EFFECTIVE_DISPLAY", cfg.Desktop.Display},
		{"VM_EFFECTIVE_RESOLUTION", cfg.Desktop.Resolution},
		{"VM_EFFECTIVE_X11_SOCKET_DIR", cfg.Desktop.X11SocketDirectory},
		{"VM_EFFECTIVE_VNC_ADDRESS", cfg.Desktop.VNCAddress},
		{"VM_EFFECTIVE_NOVNC_ADDRESS", cfg.Desktop.NoVNCAddress},
		{"VM_EFFECTIVE_NOVNC_UPSTREAM", cfg.Desktop.NoVNCUpstreamAddress},
		{"VM_EFFECTIVE_CDP_URL", cfg.Desktop.CDPURL},
		{"VM_EFFECTIVE_CHROMIUM_WATCHDOG_GRACE", strconv.Itoa(cfg.Desktop.ChromiumWatchdogGrace)},
		{"VM_EFFECTIVE_VALKEY_ADDRESS", cfg.Valkey.Address},
		{"VM_EFFECTIVE_LLAMA_ADDRESS", cfg.Llama.Address},
		{"VM_EFFECTIVE_LLAMA_CONTEXT", strconv.Itoa(cfg.Llama.ContextTokens)},
		{"VM_EFFECTIVE_MODEL_PATH", cfg.Llama.ModelPath},
		{"VM_EFFECTIVE_PROJECTOR_PATH", cfg.Llama.ProjectorPath},
		{"VM_EFFECTIVE_LLAMA_THREADS", strconv.Itoa(cfg.Llama.Threads)},
		{"VM_EFFECTIVE_TTS_ADDRESS", cfg.TTS.Address},
		{"VM_EFFECTIVE_MAIL_FLUSH_SECONDS", strconv.Itoa(cfg.Mail.FlushSeconds)},
		{"TZ", cfg.System.Timezone},
	}
	var output strings.Builder
	output.WriteString("# Generated by configctl; contains no secret values.\n")
	for _, item := range values {
		output.WriteString(item[0])
		output.WriteByte('=')
		output.WriteString(shellQuote(item[1]))
		output.WriteByte('\n')
	}
	return []byte(output.String())
}

func writeMail(loaded *config.Loaded, directory string) error {
	cfg := loaded.Config.Mail
	if err := prepareMailSpool(filepath.Join(directory, "spool"), cfg.SpoolDirectory); err != nil {
		return err
	}
	mailname := cfg.Mailname
	if mailname == "" {
		mailname, _ = os.Hostname()
	}
	var dma strings.Builder
	fmt.Fprintf(&dma, "MAILNAME %s\n", mailname)
	if cfg.Smarthost.Host != "" {
		fmt.Fprintf(&dma, "SMARTHOST %s\nPORT %d\nSTARTTLS\nSECURETRANSFER\n", cfg.Smarthost.Host, cfg.Smarthost.Port)
		if cfg.Smarthost.Username != "" && cfg.Smarthost.Password != "" {
			dma.WriteString("AUTHPATH /etc/dma/auth.conf\n")
		}
	}
	if err := config.AtomicWrite(filepath.Join(directory, "dma.conf"), []byte(dma.String())); err != nil {
		return err
	}
	auth := filepath.Join(directory, "auth.conf")
	if cfg.Smarthost.Username == "" || cfg.Smarthost.Password == "" || cfg.Smarthost.Host == "" {
		if err := os.Remove(auth); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		return nil
	}
	value := fmt.Sprintf("%s|%s:%s\n", cfg.Smarthost.Username, cfg.Smarthost.Host, cfg.Smarthost.Password)
	return config.AtomicWrite(auth, []byte(value))
}

func prepareMailSpool(defaultPath, desiredPath string) error {
	if defaultPath == desiredPath {
		info, err := os.Lstat(defaultPath)
		if errors.Is(err, os.ErrNotExist) {
			return ensureRealDirectory(defaultPath)
		}
		if err != nil {
			return err
		}
		if info.Mode()&os.ModeSymlink == 0 {
			if !info.IsDir() {
				return errors.New("mail spool path is not a directory")
			}
			return nil
		}
		previous, err := filepath.EvalSymlinks(defaultPath)
		if err != nil {
			return err
		}
		if err := os.Remove(defaultPath); err != nil {
			return err
		}
		if err := ensureRealDirectory(defaultPath); err != nil {
			return err
		}
		return migrateDirectory(previous, defaultPath)
	}
	if err := ensureRealDirectory(desiredPath); err != nil {
		return fmt.Errorf("mail spool: %w", err)
	}
	info, err := os.Lstat(defaultPath)
	if errors.Is(err, os.ErrNotExist) {
		return os.Symlink(desiredPath, defaultPath)
	}
	if err != nil {
		return err
	}
	if info.Mode()&os.ModeSymlink != 0 {
		previous, err := filepath.EvalSymlinks(defaultPath)
		if err != nil {
			return err
		}
		if filepath.Clean(previous) == desiredPath {
			return nil
		}
		if err := migrateDirectory(previous, desiredPath); err != nil {
			return err
		}
		if err := os.Remove(defaultPath); err != nil {
			return err
		}
		return os.Symlink(desiredPath, defaultPath)
	}
	if !info.IsDir() {
		return errors.New("mail spool path is not a directory")
	}
	if err := migrateDirectory(defaultPath, desiredPath); err != nil {
		return err
	}
	if err := os.Remove(defaultPath); err != nil {
		return err
	}
	return os.Symlink(desiredPath, defaultPath)
}

func ensureRealDirectory(directory string) error {
	if err := os.MkdirAll(directory, 0o700); err != nil {
		return err
	}
	info, err := os.Lstat(directory)
	if err != nil {
		return err
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.IsDir() {
		return errors.New("configured path must be a real directory")
	}
	return os.Chmod(directory, 0o700)
}

func migrateDirectory(source, destination string) error {
	if filepath.Clean(source) == filepath.Clean(destination) {
		return nil
	}
	entries, err := os.ReadDir(source)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	for _, entry := range entries {
		target := filepath.Join(destination, entry.Name())
		if _, err := os.Lstat(target); err == nil {
			return fmt.Errorf("mail spool migration target already exists: %s", entry.Name())
		} else if !errors.Is(err, os.ErrNotExist) {
			return err
		}
		if err := os.Rename(filepath.Join(source, entry.Name()), target); err != nil {
			return err
		}
	}
	return nil
}

func docs(args []string) error {
	flags := flag.NewFlagSet("docs", flag.ContinueOnError)
	output := flags.String("output", "docs/src/generated/config-reference.json", "output path")
	check := flags.Bool("check", false, "check committed output")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if flags.NArg() != 0 {
		return errors.New("docs accepts only flags")
	}
	content, err := config.DocsJSON()
	if err != nil {
		return err
	}
	if *check {
		existing, err := os.ReadFile(*output)
		if err == nil && string(existing) == string(content) {
			return nil
		}
		return fmt.Errorf("%s is stale; run `go run ./controller/cmd/configctl docs --output %s`", *output, *output)
	}
	if err := os.MkdirAll(filepath.Dir(*output), 0o755); err != nil {
		return err
	}
	if err := config.AtomicWrite(*output, content); err != nil {
		return err
	}
	return os.Chmod(*output, 0o644)
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}
